import Link from "next/link";
import { Sidebar } from "../components/dashboard/sidebar";
import { StatCard } from "../components/dashboard/stat-card";
import { Badge } from "../components/ui/badge";
import { Card } from "../components/ui/card";

const recentItems = [["ویلای نیاوران", "۲۲ شهریور ۱۴۰۳", "۴۲.۵ میلیارد تومان", "success"], ["آپارتمان سعادت‌آباد", "۲۰ شهریور ۱۴۰۳", "۱۸.۹ میلیارد تومان", "neutral"], ["آپارتمان پونک", "۱۸ شهریور ۱۴۰۳", "۹.۷ میلیارد تومان", "warning"]] as const;

export default function Dashboard() {
  return <div className="appShell"><Sidebar /><main className="mainContent"><header className="pageHeader"><div><span className="sectionKicker">دوشنبه، ۲۴ شهریور ۱۴۰۳</span><h1>صبح بخیر، مدیر دفتر</h1><p>تصمیم‌های امروز را با داده‌های روشن شروع کنید.</p></div><div className="headerActions"><Badge tone="success"><i className="statusDot" /> موتور تحلیل فعال</Badge><button className="iconButton" aria-label="اعلان‌ها">♢<i /></button></div></header>
      <section className="dashboardHero"><div><span className="heroBadge">نسخهٔ جدید موتور ارزش‌گذاری</span><h2>ارزش هر ملک را<br /><strong>با اطمینان توضیح دهید.</strong></h2><p>از بازهٔ قیمت تا نزدیک‌ترین فایل‌های مشابه؛ همه‌چیز برای یک تصمیم مستند آماده است.</p><Link className="uiButton uiButton-primary uiButton-lg" href="/valuation">شروع ارزش‌گذاری <span>←</span></Link></div><div className="heroOrb"><span>٪</span><small>توضیح‌پذیر<br />و داده‌محور</small></div></section>
      <section className="statsGrid"><StatCard label="تحلیل‌های این ماه" value="۲۴۸" detail="۱۲٪ بیشتر از ماه قبل" icon="↗" /><StatCard label="میانگین اطمینان" value="۸۲٪" detail="بر اساس ۲۴۸ تحلیل اخیر" icon="◌" tone="amber" /><StatCard label="ارزش تحت پوشش" value="۱٫۲ همت" detail="ارزش املاک تحلیل‌شده" icon="◈" tone="coral" /></section>
      <section className="dashboardGrid" id="history"><Card className="activityCard"><div className="cardToolbar"><div><span className="sectionKicker">تاریخچه</span><h2>آخرین تحلیل‌ها</h2></div><Link href="/valuation">ارزش‌گذاری جدید ←</Link></div><div className="activityTable"><div className="tableHead"><span>ملک</span><span>تاریخ</span><span>برآورد</span><span>وضعیت</span></div>{recentItems.map(([name, date, price, tone]) => <div className="tableRow" key={name}><strong>{name}</strong><span>{date}</span><b>{price}</b><Badge tone={tone}>{tone === "success" ? "اطمینان بالا" : tone === "warning" ? "در انتظار" : "تکمیل شده"}</Badge></div>)}</div></Card><Card className="insightCard"><span className="sectionKicker">بینش این هفته</span><h2>متراژ هنوز مهم‌ترین عامل است</h2><p>در ۷۲٪ از تحلیل‌های اخیر، متراژ بیشترین سهم مثبت را در برآورد قیمت داشته است.</p><div className="insightMeter"><span style={{ width: "72%" }} /></div><div className="insightFooter"><strong>۷۲٪</strong><span>سهم غالب متراژ</span></div></Card></section>
      <section className="quickSection" id="how"><div><span className="sectionKicker">سه لایهٔ اعتماد</span><h2>از حدس بازار تا تصمیم مستند</h2></div><div className="quickSteps"><article><b>۰۱</b><h3>بازه، نه عدد قطعی</h3><p>عدم‌قطعیت بازار را پنهان نمی‌کنیم.</p></article><article><b>۰۲</b><h3>مقایسهٔ واقعی</h3><p>نزدیک‌ترین معاملات را مبنای تحلیل می‌کنیم.</p></article><article><b>۰۳</b><h3>توضیح شفاف</h3><p>اثر هر ویژگی را قابل مشاهده می‌کنیم.</p></article></div></section>
      <footer className="appFooter"><strong>قیمت‌بان</strong><span>ابزار تصمیم‌یار است، نه جایگزین ارزیابی کارشناس.</span></footer>
    </main></div>;
}
